[pyprland]
plugins = [
  "scratchpads",
  "toggle_special",
  "monitors",
  "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.btop]
animation = "fromBottom"
command = "alacritty --class scratchpad-btop -e btop"
class = "scratchpad-btop"
lazy = true
size = "75% 45%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "scratchpad-pavucontrol"
lazy = true
size = "40% 40%"
unfocus = "hide"

[scratchpads.bitwarden]
animation = "fromTop"
command = "bitwarden"
class = "scratchpad-bitwarden"
size = "65% 65%"

[monitors]
unknown = "wlrlui"

# [monitors.placement]
# "Sony".top_of = ["Brand X", "Other Brand"]
# "Acer".left_end_of = "Sony"
# "MSI Gaming stuff".bottom_center_of = "(HDMI-A-1)"